### ISSUE TITLE
error when you give it the wrong order of files

### ISSUE THREAD

**Issue by msettles** [msettles/dbcAmplicons#21]
more graceful, and helpful error message needed
Wrong order of files.

dbcAmplicons preprocess -B barcodeTable2.txt -P primerTable.txt -S Judelson-sample.txt -1 Illumina_RawData/Undetermined_S0_L001_R1_001.fastq.gz -2 Illumina_RawData/Undetermined_S0_L001_I1_001.fastq.gz -3 Illumina_RawData/Undetermined_S0_L001_R2_001.fastq.gz -4 Illumina_RawData/Undetermined_S0_L001_I2_001.fastq.gz

Error message:

/home/msettles/Python_venv/local/lib/python2.7/site-packages/pkg_resources.py:991: UserWarning: /home/jli/.python-eggs is writable by group/others and vulnerable to attack when used with get_resource_filename. Consider a more secure location (set with .set_extraction_path or the PYTHON_EGG_CACHE environment variable).
  warnings.warn(msg, UserWarning)
A newer version (0.8.1-20160418) of dbcAmplicons is available at https://github.com/msettles/dbcAmplicons/tree/develop
barcode table length: 71
primer table length P5 Primer Sequences:8, P7 Primer Sequences:9
sample table length: 1, and 1 projects.
Cleaning up.
Traceback (most recent call last):
  File "build/bdist.linux-x86_64/egg/dbcAmplicons/preprocess_app.py", line 98, in start
    bcsuccesscount += read.assignBarcode(bcTable, barcodeMaxDiff)  # barcode
  File "build/bdist.linux-x86_64/egg/dbcAmplicons/sequenceReads.py", line 130, in assignBarcode
    bc2, bc2Mismatch = barcodeDist(bcTable.getP5(), self.bc_2, max_diff)
  File "build/bdist.linux-x86_64/egg/dbcAmplicons/sequenceReads.py", line 31, in barcodeDist
    bc_i, bc_mismatch = editdist.hamming_distance_list(b_l, b_2, max_diff+1)
SystemError: Bad Arguments

**Comment by msettles** [comment]
Expanded the error message to be more meaningful
