### ISSUE TITLE
validate needs primer, fix for no primer

### ISSUE THREAD

**Issue by msettles** [msettles/dbcAmplicons#28]
phoebe11@c11-42:~/MattsPipeline/CarolynsQiime/CQiime_metadata$ dbcAmplicons validate -B Carolyn_M_dbcBarcodeTable.txt -S Carolyn_M_SampleSheet2.txt --debug
/share/apps/python-2.7.4/lib/python2.7/site-packages/pkg_resources.py:1031: UserWarning: /home/phoebe11/.python-eggs is writable by group/others and vulnerable to attack when used with get_resource_filename. Consider a more secure location (set with .set_extraction_path or the PYTHON_EGG_CACHE environment variable).
  warnings.warn(msg, UserWarning)
A newer version (0.8.5) of dbcAmplicons is available at https://github.com/msettles/dbcAmplicons
barcode table length: 587
Cleaning up.
Traceback (most recent call last):
  File "build/bdist.linux-x86_64/egg/dbcAmplicons/validate_app.py", line 114, in start
    prTable = primerTable(primerFile)
  File "build/bdist.linux-x86_64/egg/dbcAmplicons/primers.py", line 39, in __init__
    prfile = open(primerfile, 'r')
TypeError: coercing to Unicode: need string or buffer, NoneType found

**Comment by msettles** [comment]
fixed
